export const CoffeCatalog = [
  {
    id: 1,
    image: "/coffee_1.png",
    tags: ["Tradicional"],
    name: "Expresso Tradicional",
    desc: "O tradicional café feito com água quente e grãos moídos",
    price: "9.90",
  },
  {
    id: 2,
    image: "/coffee_2.png",
    tags: ["Tradicional"],
    name: "Expresso Americano",
    desc: "Expresso diluído, menos intenso que o tradicional",
    price: "9.90",
  },
  {
    id: 3,
    image: "/coffee_3.png",
    tags: ["Tradicional"],
    name: "Expresso Cremoso",
    desc: "Café expresso tradicional com espuma cremosa",
    price: "9.90",
  },
  {
    id: 4,
    image: "/coffee_4.png",
    tags: ["Tradicional", "Gelado"],
    name: "Expresso Gelado",
    desc: "Bebida preparada com café expresso e cubos de gelo",
    price: "9.90",
  },
  {
    id: 5,
    image: "/coffee_5.png",
    tags: ["Tradicional", "com leite"],
    name: "Café com Leite",
    desc: "Meio a meio de expresso tradicional com leite vaporizado",
    price: "9.90",
  },
  {
    id: 6,
    image: "/coffee_6.png",
    tags: ["Tradicional", "Com leite"],
    name: "Latte",
    desc: "Uma dose de café expresso com o dobro de leite e espuma cremosa",
    price: "9.90",
  },
  {
    id: 7,
    image: "/coffee_7.png",
    tags: ["Tradicional", "com leite"],
    name: "Capuccino",
    desc: "Bebida com canela feita de doses iguais de café, leite e espuma",
    price: "9.90",
  },
  {
    id: 8,
    image: "/coffee_8.png",
    tags: ["Tradicional", "com leite"],
    name: "Macchiato",
    desc: "Café expresso misturado com um pouco de leite quente e espuma",
    price: "9.90",
  },
  {
    id: 9,
    image: "/coffee_9.png",
    tags: ["Tradicional", " com leite"],
    name: "Mocaccino",
    desc: "Café expresso com calda de chocolate, pouco leite e espuma",
    price: "9.90",
  },
  {
    id: 10,
    image: "/coffee_10.png",
    tags: ["Tradicional", "com leite"],
    name: "Chocolate Quente",
    desc: "Bebida feita com chocolate dissolvido no leite quente e café",
    price: "9.90",
  },
  {
    id: 11,
    image: "/coffee_11.png",
    tags: ["especial", "alcoólico", "gelado"],
    name: "Cubano",
    desc: "Drink gelado de café expresso com rum, creme de leite e hortelã",
    price: "9.90",
  },
  {
    id: 12,
    image: "/coffee_12.png",
    tags: ["especial"],
    name: "Havaiano",
    desc: "Bebida adocicada preparada com café e leite de coco",
    price: "9.90",
  },
  {
    id: 13,
    image: "/coffee_13.png",
    tags: ["especial"],
    name: "árabe",
    desc: "Bebida preparada com grãos de café árabe e especiarias",
    price: "9.90",
  },
  {
    id: 14,
    image: "/coffee_14.png",
    tags: ["Especial", "alcoólico"],
    name: "Irlandês",
    desc: "Bebida a base de café, uísque irlandês, açúcar e chantilly",
    price: "9.90",
  },
];
